# For more - see https://www.openfaas.com/support/

# When GitHub grants me access to the beta, I'll uncomment the below
#github: alexellis

patreon: alexellis
community_bridge: openfaas
custom: https://paypal.me/openfaas?locale.x=en_GB
open_collective: openfaas
